=== SkandaB/Foreign_Keys/HW8/catalog.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="artist_type">
        <xs:sequence>
            <xs:element ref="album" minOccurs="0" maxOccurs="100"/>
        </xs:sequence>
        <xs:attribute name="genre" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="country" type="xs:string"/>
    </xs:complexType>
    <xs:element name="artist" type="artist_type"/>
    
    <xs:complexType name="album_type">
        <xs:sequence>
            <xs:element ref="song" minOccurs="1" maxOccurs="200"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="releasedate" type="xs:date"/>
    </xs:complexType>
    <xs:element name="album" type="album_type"/>
    
    <xs:complexType name="song_type">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="length" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="song" type="song_type"/>
    

    <xs:complexType name="catalog_type">
        <xs:sequence>
            <xs:element ref="artist" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="catalog" type="catalog_type"/>
</xs:schema>

=== SkandaB/Foreign_Keys/HW8/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="catalog.xsd">

    <artist title="Red Hot Chili Peppers" country="USA" genre="Alternative Rock">
        <album title="Californication" releasedate="1999-10-10">
            <song>
                <title>Otherside</title>
                <length>170</length>
            </song>
            <song>
                <title>Scar Tissue</title>
                <length>180</length>
            </song>
            <song>
                <title>Around the World</title>
                <length>200</length>
            </song>
        </album>

        <album title="By the Way" releasedate="2003-03-04">
            <song>
                <title>Can't Stop</title>
                <length>220</length>
            </song>
            <song>
                <title>Midnight</title>
                <length>183</length>
            </song>
            <song>
                <title>Dosed</title>
                <length>203</length>
            </song>
            <song>
                <title>Cabron</title>
                <length>233</length>
            </song>
            <song>
                <title>This Is the Place</title>
                <length>209</length>
            </song>
            <song>
                <title>Throw Away Your Television</title>
                <length>253</length>
            </song>
        </album>
    </artist>

    <artist title="John Talabot" country="Spain" genre="Electronic">
        <album title="Fin" releasedate="2015-07-08">
            <song>
                <title>El Oeste</title>
                <length>175</length>
            </song>
            <song>
                <title>Depak Ine</title>
                <length>185</length>
            </song>
            <song>
                <title>Missing You</title>
                <length>210</length>
            </song>
            <song>
                <title>Last Land</title>
                <length>240</length>
            </song>
            <song>
                <title>Estiu</title>
                <length>210</length>
            </song>
        </album>
    </artist>

    <artist title="Beach House" country="USA" genre="Indie">
        <album title="Bloom" releasedate="2012-02-03">
            <song>
                <title>Myth</title>
                <length>165</length>
            </song>
            <song>
                <title>Wild</title>
                <length>185</length>
            </song>
            <song>
                <title>Lazuli</title>
                <length>210</length>
            </song>
            <song>
                <title>The Hours</title>
                <length>242</length>
            </song>
            <song>
                <title>On the Sea</title>
                <length>218</length>
            </song>
            <song>
                <title>Irene</title>
                <length>236</length>
            </song>
            <song>
                <title>Troublemaker</title>
                <length>209</length>
            </song>
        </album>
    </artist>

</catalog>
