=== SkandaB/Foreign_Keys/HW8/concert.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="concert"/>
      </xs:sequence>
      <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="concert">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="country"/>
        <xs:element ref="month"/>
      </xs:sequence>
      <xs:attribute name="title" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="country" type="xs:NCName"/>
  <xs:element name="month" type="xs:NCName"/>
</xs:schema>

=== SkandaB/Foreign_Keys/HW8/concert.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="concert.xsd">

    <concert title="Madrid Rush">
        <country>Spain</country>
        <month>April</month>
    </concert>
    <concert title="Tomorrowland">
        <country>Belgium</country>
        <month>July</month>
    </concert>
    <concert title="Adele">
        <country>USA</country>
        <month>September</month>
    </concert>
</catalog>
