=== SkandaB/Foreign_Keys/HW8/playlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="playlist"/>
      </xs:sequence>
      <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="playlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="creator"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="creator">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="song"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="song">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"/>
        <xs:element ref="length"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="length" type="xs:integer"/>
</xs:schema>

=== SkandaB/Foreign_Keys/HW8/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="playlist.xsd">
    
    <playlist name="Rock">
        <creator name="Pink">
            <song>
                <title>Around the World</title>
                <length>200</length>
            </song>
            <song>
                <title>Dosed</title>
                <length>203</length>
            </song>
            <song>
                <title>Depak Ine</title>
                <length>185</length>
            </song>
        </creator>
    </playlist>
    
    <playlist name="EDM">
        <creator name="DJ.AVB">
            <song>
                <title>Estiu</title>
                <length>210</length>
            </song>
            <song>
                <title>Dosed</title>
                <length>203</length>
            </song>
            <song>
                <title>Cabron</title>
                <length>233</length>
            </song>
        </creator>
    </playlist>
    
</catalog>
